

import 'package:get/get.dart';

class Languages extends Translations
{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US' : {
      //start
     "starttitle" : "App Doesn't Provide\nOr Suggest Any Diagnosis",
        "startdesc" : "Please Use This App Only To\nCommunicate The Results To Your\nTherapist Or Mental Health\nProfessional.",
       //report
      "firstline" : "Thank you for taking the time to complete the self-assessments.",
      "secline" : "Your score is",
      "thirdline" : "which indicates",
      "forthline" : "Based on your assessment results,",
      "fifthline" : "We suggest you consult a mental health professional.",
      "sixthline" : "If you live in the UK you can access the below link to contact your local Mental Health Services:",
      "sevenline" : "Search for your GP - Find an NHS talking therapies service - NHS",
      "mild" : "Mild",
      "mod" : "Moderate",
      "severe" : "Severe",
      "op1" : "No Anxiety disorder",
      "op2" : "Mild Anxiety disorder",
      "op3" : "Moderate Anxiety disorder",
      "op4" : "Severe Anxiety disorder",
      "op5" : "No Depression",
      "op6" : "Mild Depression",
      "op7" : "Moderate Depression",
      "op8" : "Moderate Severe Depression",
      "op9" : "Severe Depression",
      "op10" : "Minimal impairment",
      "op11" : "Mild impairment",
      "op12" : "Moderate impairment",
      "op13" : "Severe impairment",
      "op14" : "No Anxiety disorder and depression",
      "op15" : "Mild Anxiety disorder and depression",
      "op16" : "Moderate Anxiety disorder and depression",
      "op17" : "Severe Anxiety disorder and depression",







      ////////////
      "title" : "Mental Health Assessment App",
      "dashhello" : "Hello There!",
      "dashslogan" : "Lets Assess Your Mental Health",
      "wsastop" : "Please indicate how much your work or social life has been impaired by your symptoms over the past week",
      "toptext" : "Over the past two weeks, how often have you been bothered by the following problems?",
      "qtnumber" : "Question",
      //Titles
      "g7title" : "Generalised Anxiety Disorder (GAD-7)",
      "p9title" : "Patient Health Questionnaire (PHQ-9)",
      "wsastitle" : "Work and Social Adjustment scale (WSAS)",
      //G7
      "g71" : "Feeling nervous, anxious or on edge.",
      "g72" : "Not being able to stop or control worrying.",
      "g73" : "Worrying too much about different things.",
      "g74" : "Trouble relaxing.",
      "g75" : "Being so restless that it is hard to sit still.",
      "g76" : "Becoming easily annoyed or irritable.",
      "g77" : "Feeling afraid, as if something awful might happen.",
      "op1" : "Not at all",
      "op2" : "Several days",
      "op3" : "More than half the days",
      "op4" : "Nearly every day",
      //P9
      "p91" : "Little interest or pleasure in doing things.",
      "p92" : "Feeling down, depressed, or hopeless.",
      "p93" : "Trouble falling or staying asleep, or sleeping too much.",
      "p94" : "Feeling tired or having little energy.",
      "p95" : "Poor appetite or overeating.",
      "p96" : "Feeling bad about yourself - or that you are a failure or have let yourself or your family down.",
      "p97" : "Trouble concentrating on things, such as reading the newspaper or watching television.",
      "p98" : "Moving or speaking so slowly that other people could have noticed? Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual.",
      "p99" : "Thoughts that you would be better off dead, or of hurting yourself in some way.",
      //WSAS
      "wsas1" : "Personal relationships (e.g., family, friends, colleagues)",
      "wsas2" : "Work or studies (e.g., absenteeism, reduced productivity)",
      "wsas3" : "Home management (e.g., maintaining home, performing chores)",
      "wsas4" : "Social leisure activities (e.g., hobbies, sports, entertainment)",
      "wsas5" : "Private leisure activities (e.g., reading, listening to music, watching TV)",
      "wp1" : "Not at all impaired",
      "wp2" : "Slightly impaired",
      "wp3" : "Moderately impaired",
      "wp4" : "Markedly impaired",
      "wp5" : "Severely impaired",

    },

  'ur_PK' : {
  "starttitle": "ایپ کوئی\nتشخیص فراہم نہیں کرتی یا تجویز نہیں کرتی",
  "startdesc": "براہ کرم اپنے تھراپسٹ یا دماغی صحت کے پیشہ ور کو نتائج کو موصول کرنے کے لیے اس ایپ کا استعمال کریں۔",
  "firstline": "آپ کو وقت دینے کا شکریہ کہ ذاتی جانچ پڑتال مکمل کرنے کا۔",
  "secline": "آپ کا نمبر ہے",
  "thirdline": "جو کہ ظاہر ہے",
  "forthline": "آپ کی جانچ کے نتائج کے بنیاد پر،",
  "fifthline": "ہم آپ کو دماغی صحت کے ماہر سے مشاورت کرنے کی تجویز دیتے ہیں۔",
  "sixthline": "اگر آپ رہائشیں رکھتے ہیں تو آپ اپنے مقامی دماغی صحت خدمات سے رابطہ کرنے کے لیے نیچے دیے گئے لنک کا استعمال کرسکتے ہیں:",
  "sevenline": "اپنے ڈاکٹر کی تلاش کریں - ایک این ایچ ایس بولنگ علاج کی خدمات تلاش کریں - این این ایچ ایس",
  "mild": "ہلکا",
  "mod": "معتدل",
  "severe": "شدید",
  "op1": "کوئی تشویش کی بیماری نہیں",
  "op2": "ہلکی تشویش کی بیماری",
  "op3": "معتدل تشویش کی بیماری",
  "op4": "شدید تشویش کی بیماری",
  "op5": "کوئی افسردگی نہیں",
  "op6": "ہلکی افسردگی",
  "op7": "معتدل افسردگی",
  "op8": "معتدل شدید افسردگی",
  "op9": "شدید افسردگی",
  "op10": "کمیت کا نقصان",
  "op11": "ہلکی کمیت",
  "op12": "معتدل کمیت",
  "op13": "شدید کمیت",
  "op14": "کوئی تشویش کی بیماری اور افسردگی نہیں",
  "op15": "ہلکی تشویش کی بیماری اور افسردگی",
  "op16": "معتدل تشویش کی بیماری اور افسردگی",
  "op17": "شدید تشویش کی بیماری اور افسردگی",
  "title" : "مینٹل صحت کا اندازہ ایپ" ,
  "dashhello" : "ہیلو وہاں!" ,
  "dashslogan" : "آؤ اپنی مینٹل صحت کا اندازہ لگائیں",
  "wsastop" : "براہ کرم بتائیں کہ آپ کے علامات کی وجہ سے آپ کے کام یا سماجی زندگی پر پچھیدگی کتنی ہوئی ہے پچھلے ہفتے میں",
  "toptext" : "پچھلے دو ہفتوں میں، آپ کو کتنی بار نیچے دیے گئے مسائل سے پریشانی ہوئی؟",
  "qtnumber" : "سوال",
  //Titles
  "g7title" : "جنرلائزڈ اینکشائٹی بےقابو (GAD-7)",
  "p9title" : "پیشنٹ ہیلتھ کوئسچنئیر (PHQ-9)",
  "wsastitle" : "کام اور سوشل ایڈجسٹمنٹ اسکیل (WSAS)",
  //G7
  "g71" : "پریشان یا گھبراہٹ کا احساس۔",
  "g72" : "پریشانی کو روکنے یا کنٹرول کرنے کی صلاحیت نہ ہونا۔",
  "g73" : "بہت سی چیزوں کی بے چینی۔",
  "g74" : "آرام کرنے میں مشکل۔",
  "g75" : "اتنی بے چین ہونا کہ بیٹھنا مشکل ہو۔",
  "g76" : "آسانی سے غصے یا غصہ آنا۔",
  "g77" : "کچھ خوفناک ہونے کا احساس۔",
  "op1" : "بالکل نہیں",
  "op2" : "کئی دن",
  "op3" : "زیادہ سے زیادہ دنوں",
  "op4" : "تقریبا ہر دن",
  //P9
  "p91" : "کام کرنے میں دلچسپی یا خوشی کا کم ہونا۔",
  "p92" : "اداسی، غمگین یا مایوس محسوس کرنا۔",
  "p93" : "سونے میں مشکل، یا سوتے رہنے کی مشکل، یا بہت زیادہ سونا۔",
  "p94" : "تھکاوٹ یا کم توانائی محسوس کرنا۔",
  "p95" : "بھوک کم ہونا یا زیادہ کھانا۔",
  "p96" : "خود پر برا محسوس کرنا - یا یہ سوچنا کہ آپ ناکام ہیں یا آپ نے خود کو یا اپنے خاندان کو خستہ کر دیا ہے۔",
  "p97" : "چیزوں پر توجہ دینے میں مشکل، جیسے اخبار پڑھنا یا ٹیلی ویژن دیکھنا۔",
  "p98" : "اور لوگوں کو نوٹس نہیں کرنے دینا؟ یا الٹی طرف - اتنی بے چینی کہ آپ کافی زیادہ آرام سے حرکت کر رہے ہیں۔",
  "p99" : "خود کو بہتر ہونے کا خیال یا کسی طرح اپنے آپ کو زخمی کرنے کی خیالات؟",
  //WSAS
  "wsas1" : "ذاتی تعلقات (مثلاً خاندان، دوست، ساتھی)",
  "wsas2" : "کام یا مطالعے (مثلاً غیر حاضری، کم پیدائش)",
  "wsas3" : "گھر کی مدیریت (مثلاً گھر کی دیکھ بھال، کاموں کا انجام)",
  "wsas4" : "سوشل لیجر انشاعات (مثلاً سرگرمیاں، کھیل، تفریح)",
  "wsas5" : "نجی لیجر انشاعات (مثلاً کتابیں پڑھنا، موسیقی سننا، ٹیلی ویژن دیکھنا)",
  "wp1" : "بالکل معیوب نہیں",
  "wp2" : "تھوڑی مقدار میں معیوب",
  "wp3" : "متوسط ​​طور پر معیوب",
  "wp4" : "نمایاں طور پر معیوب",
  "wp5" : "شدید طور پر معیوب",

  },

//polish

  'pl_PL' : {
  "starttitle": "Aplikacja nie dostarcza\nani nie sugeruje żadnej diagnozy",
  "startdesc": "Proszę korzystać z tej aplikacji tylko\ndo przekazywania wyników swojemu\nterapeucie lub specjaliście od zdrowia psychicznego.",
  "firstline": "Dziękujemy za poświęcenie czasu na wypełnienie samoocen.",
  "secline": "Twój wynik to",
  "thirdline": "co wskazuje na",
  "forthline": "Na podstawie wyników oceny,",
  "fifthline": "sugerujemy skonsultowanie się z profesjonalistą ds. zdrowia psychicznego.",
  "sixthline": "Jeśli mieszkasz w Wielkiej Brytanii, możesz skorzystać z poniższego linku, aby skontaktować się z lokalnymi służbami zdrowia psychicznego:",
  "sevenline": "Szukaj swojego lekarza - Znajdź usługę terapii rozmownej NHS - NHS",
  "mild": "Łagodny",
  "mod": "Umiarkowany",
  "severe": "Ciężki",
  "op1": "Brak zaburzeń lękowych",
  "op2": "Łagodne zaburzenia lękowe",
  "op3": "Umiarkowane zaburzenia lękowe",
  "op4": "Ciężkie zaburzenia lękowe",
  "op5": "Brak depresji",
  "op6": "Łagodna depresja",
  "op7": "Umiarkowana depresja",
  "op8": "Umiarkowanie ciężka depresja",
  "op9": "Ciężka depresja",
  "op10": "Minimalne upośledzenie",
  "op11": "Łagodne upośledzenie",
  "op12": "Umiarkowane upośledzenie",
  "op13": "Ciężkie upośledzenie",
  "op14": "Brak zaburzeń lękowych i depresji",
  "op15": "Łagodne zaburzenia lękowe i depresja",
  "op16": "Umiarkowane zaburzenia lękowe i depresja",
  "op17": "Ciężkie zaburzenia lękowe i depresja",
  "title": "Aplikacja do oceny zdrowia psychicznego",
  "dashhello": "Cześć!",
  "dashslogan": "Oceny twoje zdrowie psychiczne",
  "wsastop": "Proszę określić, jak bardzo twoja praca lub życie społeczne zostały zaburzone przez twoje objawy w ciągu ostatniego tygodnia",
  "toptext": "W ciągu ostatnich dwóch tygodni, jak często dotykają cię następujące problemy?",
  "qtnumber": "Pytanie",
  //Titles
  "g7title": "Zaburzenie lękowe uogólnione (GAD-7)",
  "p9title": "Kwestionariusz Zdrowia Pacjenta (PHQ-9)",
  "wsastitle": "Skala Przystosowania do Pracy i Życia Społecznego (WSAS)",
  //G7
  "g71": "Czujesz się nerwowo, zaniepokojony lub zdenerwowany.",
  "g72": "Nie potrafisz przestać lub kontrolować zmartwień.",
  "g73": "Zbyt wiele martwisz się różnymi rzeczami.",
  "g74": "Trudności z relaksem.",
  "g75": "Jesteś tak niespokojny, że trudno ci usiedzieć na miejscu.",
  "g76": "Łatwo się irytujesz lub drażnisz.",
  "g77": "Czujesz się przerażony, jakby coś strasznego mogło się wydarzyć.",
  "op1": "Wcale",
  "op2": "Przez kilka dni",
  "op3": "Więcej niż połowę dni",
  "op4": "Prawie codziennie",
  //P9
  "p91": "Mało zainteresowania lub przyjemności w wykonywaniu czynności.",
  "p92": "Czujesz się przygnębiony, smutny lub beznadziejny.",
  "p93": "Trudności z zasypianiem lub utrzymaniem snu, albo zbyt dużo spania.",
  "p94": "Czujesz się zmęczony lub masz mało energii.",
  "p95": "Zły apetyt lub objadanie się.",
  "p96": "Czujesz się źle o sobie - lub że jesteś nieudacznikiem lub zawiodłeś siebie lub swoją rodzinę.",
  "p97": "Trudności z koncentracją na rzeczach, takich jak czytanie gazety lub oglądanie telewizji.",
  "p98": "Poruszasz się lub mówisz tak wolno, że inni mogli zauważyć? Albo przeciwnie - jesteś taki nerwowy lub niespokojny, że się dużo więcej ruszasz niż zwykle.",
  "p99": "Myśli, że byłbyś lepiej martwy, albo o skrzywdzeniu siebie w jakiś sposób.",
  //WSAS
  "wsas1": "Relacje osobiste (np. rodzina, przyjaciele, koledzy)",
  "wsas2": "Praca lub nauka (np. absencja, zmniejszona produktywność)",
  "wsas3": "Zarządzanie domem (np. utrzymanie domu, wykonywanie obowiązków)",
  "wsas4": "Aktywności społeczne rekreacyjne (np. hobby, sport, rozrywka)",
  "wsas5": "Aktywności prywatne rekreacyjne (np. czytanie, słuchanie muzyki, oglądanie telewizji)",
  "wp1": "Wcale nie upośledzone",
  "wp2": "Trochę upośledzone",
  "wp3": "Średnio upośledzone",
  "wp4": "Znacznie upośledzone",
  "wp5": "Bardzo znacznie upośledzone"
  },

  ///punjabi

 'pa_IN': {
  "starttitle": "ਐਪ ਕੋਈ ਡਾਈਗਨੋਸਿਸ ਨਹੀਂ ਪ੍ਰਦਾਨ ਕਰਦਾ\nਜਾਂ ਸੁਝਾਅ ਨਹੀਂ ਕਰਦਾ",
  "startdesc": "ਕਿਰਪਾ ਕਰਕੇ ਇਸ ਐਪ ਨੂੰ ਸਿਰਫ ਤੁਹਾਡੇ ਨਤੀਜਿਆਂ ਨੂੰ ਤੁਹਾਡੇ ਥੈਰਾਪਿਸਟ ਜਾਂ ਮਾਨਸਿਕ ਸਿਹਤ ਪੇਸ਼ੇਵਰ ਨੂੰ ਸੁਨਾਉਣ ਲਈ ਵਰਤੋ।",
  "firstline": "ਆਪਣੇ ਸਵ-ਮੂਲਾਂਕਣ ਪੂਰਾ ਕਰਨ ਲਈ ਸਮਰਪਨ ਕਰਨ ਲਈ ਧੰਨਵਾਦ।",
  "secline": "ਤੁਹਾਡਾ ਸਕੋਰ ਹੈ",
  "thirdline": "ਜੋ ਇਸ ਨੂੰ ਦਿਖਾਉਂਦਾ ਹੈ",
  "forthline": "ਆਪਣੀ ਮੂਲਾਂਕਣ ਦੇ ਨਤੀਜੇ ਦੇ ਆਧਾਰ ਤੇ,",
  "fifthline": "ਅਸੀਂ ਤੁਹਾਨੂੰ ਮਾਨਸਿਕ ਸਿਹਤ ਪੇਸ਼ੇਵਰ ਨਾਲ ਸਲਾਹ ਦੇਂਦੇ ਹਾਂ।",
  "sixthline": "ਜੇ ਤੁਸੀਂ ਯੂ.ਕੇ. ਵਿੱਚ ਰਹਿੰਦੇ ਹੋ ਤਾਂ ਤੁਸੀਂ ਆਪਣੇ ਸਥਾਨਿਕ ਮਾਨਸਿਕ ਸਿਹਤ ਸੇਵਾਵਾਂ ਨਾਲ ਸੰਪਰਕ ਕਰਨ ਲਈ ਹੇਠ ਦਿੱਤੇ ਲਿੰਕ ਦੀ ਵਰਤੋਂ ਕਰ ਸਕਦੇ ਹੋ:",
  "sevenline": "ਆਪਣਾ ਜੀ.ਪੀ. ਲੱਭੋ - ਇੱਕ ਐਨ ਐਚ ਐਸ ਗੱਲਬਾਤ ਦੀ ਸ਼ੇਰੋਕੀ ਸੇਵਾ - ਐਨ ਐਚ ਐਸ",
  "mild": "ਹਲਕਾ",
  "mod": "ਦਰਮਿਆਨੀ",
  "severe": "ਤੀਵ੍ਹਾ",
  "op1": "ਕੋਈ ਚਿੰਤਾ ਬਿਮਾਰੀ ਨਹੀਂ",
  "op2": "ਹਲਕੀ ਚਿੰਤਾ ਬਿਮਾਰੀ",
  "op3": "ਦਰਮਿਆਨੀ ਚਿੰਤਾ ਬਿਮਾਰੀ",
  "op4": "ਤੀਵ੍ਹੀ ਚਿੰਤਾ ਬਿਮਾਰੀ",
  "op5": "ਕੋਈ ਉਦਾਸੀ",
  "op6": "ਹਲਕੀ ਉਦਾਸੀ",
  "op7": "ਮਧਿਆਨ ਉਦਾਸੀ",
  "op8": "ਦਰਮਿਆਨੀ ਤੇਜ਼ ਉਦਾਸੀ",
  "op9": "ਤੇਜ਼ ਉਦਾਸੀ",
  "op10": "ਘੱਟੀ ਹੋਈ ਅਸਥਿਤੀ",
  "op11": "ਹਲਕੀ ਅਸਥਿਤੀ",
  "op12": "ਦਰਮਿਆਨੀ ਅਸਥਿਤੀ",
  "op13": "ਤੇਜ਼ ਅਸਥਿਤੀ",
  "op14": "ਕੋਈ ਚਿੰਤਾ ਬਿਮਾਰੀ ਅਤੇ ਉਦਾਸੀ",
  "op15": "ਹਲਕੀ ਚਿੰਤਾ ਬਿਮਾਰੀ ਅਤੇ ਉਦਾਸੀ",
  "op16": "ਦਰਮਿਆਨੀ ਚਿੰਤਾ ਬਿਮਾਰੀ ਅਤੇ ਉਦਾਸੀ",
  "op17": "ਤੇਜ਼ ਚਿੰਤਾ ਬਿਮਾਰੀ ਅਤੇ ਉਦਾਸੀ",
  "title": "ਮਾਨਸਿਕ ਸਿਹਤ ਮੁਲਾਂਕਣ ਐਪ",
  "dashhello": "ਹੈਲੋ!",
  "dashslogan": "ਆਓ ਤੁਹਾਡੀ ਮਾਨਸਿਕ ਸਿਹਤ ਨੂੰ ਮੁਲਾਂਕਣ ਕਰੀਏ।",
  "wsastop": "ਕਿਰਪਾ ਕਰਕੇ ਦਸੋ ਕਿ ਤੁਹਾਡੇ ਲੱਛਣਾਂ ਦੇ ਕਾਰਨ ਪਿਛਲੇ ਹਫਤੇ ਤੁਹਾਡੀ ਕੰਮ ਜਾਂ ਸਮਾਜਿਕ ਜੀਵਨ ਨੂੰ ਕਿੰਨਾ ਅਸਰ ਪੈ ਗਿਆ ਹੈ।",
  "toptext": "ਪਿਛਲੇ ਦੋ ਹਫਤੇ, ਕਿਤਨੀ ਵਾਰ ਤੁਹਾਨੂੰ ਹੇਠਾਂ ਦੇ ਮਸਲਿਆਂ ਦੀ ਪਰੇਸ਼ਾਨੀ ਹੋਈ ਹੈ?",
  "qtnumber": "ਸਵਾਲ",
  //ਸਿਰਲੇਖ
  "g7title": "ਸਾਮਾਨਿਆ ਚਿੰਤਾ ਬਿਮਾਰੀ (GAD-7)",
  "p9title": "ਪੇਸ਼ੇਂਟ ਹੈਲਥ ਐਸਿੱਸਮੈਂਟ ਐਪ (PHQ-9)",
  "wsastitle": "ਕੰਮ ਅਤੇ ਸਮਾਜਿਕ ਸੰਵਾਰਨ ਸਕੇਲ (WSAS)",
  //G7
  "g71": "ਘਬਰਾਹਟ, ਉਨਸੁਖਾਹਟ ਜਾਂ ਤੰਗੀ ਮਹਿਸੂਸ ਕਰਨਾ।",
  "g72": "ਚਿੰਤਾ ਨਾਲ ਰੁਕਣਾ ਜਾਂ ਨਿਯੰਤਰਿਤ ਕਰਨ ਦੀ ਸਮਰੱਥਾ ਨਾ ਹੋਣਾ।",
  "g73": "ਵਿਭਿਨਨ ਚੀਜ਼ਾਂ ਬਾਰੇ ਬਹੁਤ ਚਿੰਤਾ ਕਰਨਾ।",
  "g74": "ਆਰਾਮ ਨਾਲ ਰਹਿਣ ਦੀ ਮੁਸ਼ਕਲ।",
  "g75": "ਇਤਨੀ ਬੇਚੈਨੀ ਹੋਣਾ ਕਿ ਬੈਠਣਾ ਮੁਸ਼ਕਲ ਹੈ।",
  "g76": "ਆਸਾਨੀ ਨਾਲ ਚਢਿਆ ਜਾਣਾ ਜਾਂ ਉਸ ਤੱਕ ਪਹੁੰਚਣਾ ਜਿੱਥੇ ਆਮ ਤੌਰ 'ਤੇ ਗੁਸਾ ਆਉਂਦਾ ਹੈ।",
  "g77": "ਕੁਝ ਡਰ ਹੋਣ ਦਾ ਮਹਿਸੂਸ ਕਰਨਾ, ਜਿਵੇਂ ਕੋਈ ਖੋਜੀਮਤ ਹੋ ਰਹੀ ਹੋ।",
  "op1": "ਬਿਲਕੁਲ ਨਹੀਂ",
  "op2": "ਕੁਝ ਦਿਨ",
  "op3": "ਆਧੇ ਤੋਂ ਵੱਧ ਦਿਨ",
  "op4": "ਲੱਗਭੱਗ ਹਰ ਦਿਨ",
  //P9
  "p91": "ਕਾਰਜ ਵਿੱਚ ਦਿਲਚਸਪੀ ਜਾਂ ਸੁਖ ਦੀ ਕਮੀ।",
  "p92": "ਨਕਾਮ, ਉਦਾਸੀ ਜਾਂ ਨਿਰਾਸ਼ਾ ਮਹਿਸੂਸ ਕਰਨਾ।",
  "p93": "ਸੌਣ ਵਿੱਚ ਮੁਸ਼ਕਲ, ਯਾ ਨੰਗਾਹਟ ਰੱਖਣ ਜਾਂ ਬਹੁਤ ਜਿਆਦਾ ਸੌਣਾ।",
  "p94": "ਥਕਾਵਟ ਮਹਿਸੂਸ ਕਰਨਾ ਜਾਂ ਥੋੜੀ ਊਰਜਾ ਹੋਣਾ।",
  "p95": "ਖਰਾਬ ਭੁਖ ਜਾਂ ਜ਼ਿਆਦਾ ਖਾਣਾ।",
  "p96": "ਆਪਣੇ ਬਾਰੇ ਬੁਰਾ ਮਹਿਸੂਸ ਕਰਨਾ - ਜਾਂ ਤੁਸੀਂ ਅਪਣੇ ਆਪ ਨੂੰ ਅਸਫਲ ਮਹਿਸੂਸ ਕਰਦੇ ਹੋ ਜਾਂ ਆਪਣੇ ਪਰਿਵਾਰ ਨੂੰ ਠੱਗਣ ਜਾਂ ਆਪਣੀ ਕਮਾਈ ਵਿੱਚ ਹਾਨੀ ਪਹੁੰਚਾਉਣਾ ਹੈ।",
  "p97": "ਚੀਜ਼ਾਂ 'ਤੇ ਧਿਆਨ ਕੇਂਦਰਤ ਹੋਣ 'ਤੇ ਮੁਸ਼ਕਲਾਂ, ਜਿਵੇਂ ਕਿ ਅਖ਼ਬਾਰ ਪੜ੍ਹਨਾ ਜਾਂ ਟੀਵੀ ਦੇਖਣਾ।",
  "p98": "ਕਿ ਤੁਸੀਂ ਇਤਨੇ ਧੀਮੇ ਗਤੀ ਨਾਲ ਹਿਲ ਰਹੇ ਹੋ ਕਿ ਦੂਜੇ ਵਿਅਕਤੀ ਨੂੰ ਨੋਟ ਕਰਨਾ ਮੁਸ਼ਕਿਲ ਹੈ? ਜਾਂ ਉਲਟਾ - ਤੁਸੀਂ ਇਤਨੇ ਅੱਧਰਜਨਕ ਜਾਂ ਬੇਚੈਨ ਹੋ ਕਿ ਤੁਸੀਂ ਸਾਨੂੰ ਆਮ ਤੌਰ 'ਤੇ ਹਿਲਦੇ ਹੋ ਕਿ ਤੁਸੀਂ ਹਾਲਤ ਅਤੇ ਆਵਾਜਾਈ ਨੂੰ ਨੋਟਿਸ ਕਰਦੇ ਹੋ।",
  "p99": "ਤੁਹਾਨੂੰ ਮਰਨ ਲਈ ਭਲਾ ਮਹਿਸੂਸ ਕਰਦੇ ਹੋ, ਜਾਂ ਕਿਸੇ ਤਰ੍ਹਾਂ ਆਪਣੇ ਆਪ ਨੂੰ ਚੋਟ ਪਹੁੰਚਾਉਣ ਦੀ ਸੋਚਦੇ ਹੋ।",
  //WSAS
  "wsas1": "ਨਿੱਜੀ ਸੰਬੰਧ (ਜਿਵੇਂ ਕਿ ਪਰਿਵਾਰ, ਦੋਸਤ, ਸਹਿਕਾਰੀ)",
  "wsas2": "ਕੰਮ ਜਾਂ ਅਧਿਆਪਨ (ਜਿਵੇਂ ਕਿ ਗਈ ਹਾਜ਼ਰੀ, ਘਟਿਆ ਉਤਪਾਦਕਤਾ)",
  "wsas3": "ਘਰ ਦੀ ਪ੍ਰਬੰਧਨ (ਜਿਵੇਂ ਕਿ ਘਰ ਦੀ ਦੇਖਭਾਲ, ਕੰਮ ਕਰਨਾ)",
  "wsas4": "ਸਮਾਜਿਕ ਮਨੋਰੰਜਨ ਸਰੋਤ (ਜਿਵੇਂ ਕਿ ਸ਼ੌਕ, ਖੇਡ, ਟਿੱਖਣਾ)",
  "wsas5": "ਨਿੱਜੀ ਮਨੋਰੰਜਨ ਸਰੋਤ (ਜਿਵੇਂ ਕਿ ਪੜ੍ਹਾਈ, ਸੁਣਨਾ, ਟੀਵੀ ਦੇਖਣਾ)",
  "wp1": "ਬਿਲਕੁਲ ਪ੍ਰਭਾਵਿਤ ਨਹੀਂ",
  "wp2": "ਥੋੜੀ ਹੋਇਆ ਹੈ",
  "wp3": "ਔਸਤ ਤੋਂ ਅਧਿਕ ਪ੍ਰਭਾਵਿਤ",
  "wp4": "ਜ਼ਰਾ ਪ੍ਰਭਾਵਿਤ",
  "wp5": "ਬਹੁਤ ਪ੍ਰਭਾਵਿਤ"
  },


//bengali

  'bn_BD':{

  "starttitle": "অ্যাপটি কোনও বিনামূল্যে\nডায়াগনোসিস প্রদান বা সুপারিশ করে না",
  "startdesc": "অনুগ্রহ করে এই অ্যাপটি ব্যবহার করুন শুধুমাত্র\nআপনার ফলাফলগুলি আপনার চিকিৎসক বা মানসিক স্বাস্থ্য\nপেশাদার জানাতে।",
  "firstline": "আপনার স্ব-মূল্যায়ন সম্পন্ন করার জন্য সময় দেয়ার জন্য ধন্যবাদ।",
  "secline": "আপনার স্কোর হল",
  "thirdline": "যা নির্দেশ করে",
  "forthline": "আপনার মূল্যায়নের ফলাফল ভিত্তিক,",
  "fifthline": "আমরা আপনাকে একজন মানসিক স্বাস্থ্য পেশাদার সাথে পরামর্শ করছি।",
  "sixthline": "আপনি যদি যুক্তরাষ্ট্রে থাকেন তাহলে আপনি নিচের লিংক ব্যবহার করে\nআপনার স্থানীয় মানসিক স্বাস্থ্য পরিষেবা সাথে যোগাযোগ করতে পারেন:",
  "sevenline": "আপনার জিপি খুঁজুন - একটি এনএচএস টকিং থেরাপি সেবা খুঁজুন - এনএচএস",
  "mild": "হালকা",
  "mod": "মাঝামাঝি",
  "severe": "গম্ভীর",
  "op1": "কোনও উদ্বিগ্নতা ব্যাধি নেই",
  "op2": "হালকা উদ্বিগ্নতা ব্যাধি",
  "op3": "মাঝামাঝি উদ্বিগ্নতা ব্যাধি",
  "op4": "গম্ভীর উদ্বিগ্নতা ব্যাধি",
  "op5": "কোনও বিষণ্ণতা নেই",
  "op6": "হালকা বিষণ্ণতা",
  "op7": "মাঝামাঝি বিষণ্ণতা",
  "op8": "মাঝামাঝি গভীর বিষণ্ণতা",
  "op9": "গভীর বিষণ্ণতা",
  "op10": "ন্যুনতম অসমর্থন",
  "op11": "হালকা অসমর্থন",
  "op12": "মাঝামাঝি অসমর্থন",
  "op13": "গভীর অসমর্থন",
  "op14": "কোনও উদ্বিগ্নতা ও বিষণ্ণতা নেই",
  "op15": "হালকা উদ্বিগ্নতা ও বিষণ্ণতা",
  "op16": "মাঝামাঝি উদ্বিগ্নতা ও বিষণ্ণতা",
  "op17": "গম্ভীর উদ্বিগ্নতা ও বিষণ্ণতা",
  "title": "মানসিক স্বাস্থ্য মূল্যায়ন অ্যাপ",
  "dashhello": "হ্যালো!",
  "dashslogan": "আসুন আপনার মানসিক স্বাস্থ্য মূল্যায়ন করি।",
  "wsastop": "দয়া করে বলুন কতটা আপনার কাজ বা সামাজিক জীবনকে গত সপ্তাহে আপনার লক্ষণগুলি দ্বারা আপত্তি হয়েছে",
  "toptext": "গত দুই সপ্তাহে, কত বার নিম্নলিখিত সমস্যাগুলি আপনাকে বিরক্ত করেছে?",
  "qtnumber": "প্রশ্ন",
  //শিরোনাম
  "g7title": "সাধারণ উত্তেজনা ব্যাধি (GAD-7)",
  "p9title": "রোগীর স্বাস্থ্য প্রশ্নোত্তর (PHQ-9)",
  "wsastitle": "কর্ম এবং সামাজিক অবস্থান মাপ (WSAS)",
  //G7
  "g71": "নব্যতা, উদ্বিগ্নতা বা অবসাদের মধ্যে অনুভব করা।",
  "g72": "চিন্তা বন্ধ করতে বা নিয়ন্ত্রণ করতে পারতেন না।",
  "g73": "বিভিন্ন বিষয়ে অনেক চিন্তা করা।",
  "g74": "বিশ্রামে সমস্যা।",
  "g75": "এত অশান্ত হয়ে থাকা যাতে এটি কঠিন বসবাস করা।",
  "g76": "সহজে উত্তেজিত বা ক্রোধান্বিত হয়ে যাওয়া।",
  "g77": "কিছু ভয় অনুভব করা, যেমন কিছু আবিষ্ট হতে পারে।",
  "op1": "কোনও না",
  "op2": "কিছু দিন",
  "op3": "অধিকাংশ দিন",
  "op4": "প্রায় প্রতিদিন",
  //P9
  "p91": "কাজে কিংবা মনোরম হয়ে কিছুটা আগ্রহ নেই।",
  "p92": "নিঃশ্বাস, অবসাদ, অথবা নিরাপদের অনুভব করা।",
  "p93": "ঘুম না পাওয়া বা থাকা অথবা বেশি ঘুমানো বা ঘুমানো সমস্যা।",
  "p94": "অবসাদে বা বেশি প্রাণিতে অবসাদের অনুভব করা।",
  "p95": "খাওয়া-ফাঁসি বা বেশি খাওয়া।",
  "p96": "নিজের বারে খারাপ অনুভব করা - বা আপনি নিজেকে অসফল বা আপনার পরিবারে অসফল অথবা নিজেকে অসফল মনে করা।",
  "p97": "বিষয়ে মনে রাখা, যেমন সংবাদপত্র পড়া বা টেলিভিশন দেখা।",
  "p98": "আপনি কি ইতনে ধীরে যাচ্ছেন যে অন্যেরা নোটিশ করতে পারে? অথবা উল্টা - আপনি কি তত্ত্বাবধানে বা অতিরিক্ত অস্থির হয়েছেন যে আপনি সাধারণত একাধিক চলচ্চিত্র বা অন্য জিনিসের চালনা করেছেন।",
  "p99": "মর্ডার অথবা নিজের ক্ষতির জন্য আপনি মনে করেছেন যে ভাল হবেন।",
  //WSAS
  "wsas1": "ব্যক্তিগত সম্পর্ক (যেমন: পরিবার, বন্ধু, সহকর্মী)",
  "wsas2": "কাজ বা অধ্যয়ন (যেমন: অনুপস্থিতি, হ্রাসমান উত্পাদকতা)",
  "wsas3": "বাড়ির ব্যবস্থাপনা (যেমন: বাড়ি রক্ষা, কর্ম সম্পাদন)",
  "wsas4": "সামাজিক বিনোদনের কার্যক্রম (যেমন: শখ, খেলা, বিনোদন)",
  "wsas5": "নিজস্ব বিনোদনের কার্যক্রম (যেমন: পড়া, সংগীত শোনা, টেলিভিশন দেখা)",
  "wp1": "পুরোপুরি আপত্তি হয় না",
  "wp2": "স্লাইটলি আপত্তি হয়েছে",
  "wp3": "মধ্যমতার আপত্তি হয়েছে",
  "wp4": "চরম পরিমাপে আপত্তি হয়েছে",
  "wp5": "অত্যন্ত পরিমাপে আপত্তি হয়েছে"
  },


  /// Gujarati

  'gu_IN':{

  "starttitle": "ઍપ કોઈ ડાયાગ્નોસિસ પ્રદાન કરતું નથી\nઅથવા સૂચવવું નથી",
  "startdesc": "કૃપા કરીને આ ઍપનો ઉપયોગ કરો માત્ર તમારા પરિણામોને તમારા\nથેરેપિસ્ટ અથવા માનસિક સ્વાસ્થ્ય વિશેષજ્ઞને સૂચવવા માટે.",
  "firstline": "તમારા સ્વ-મૂલ્યાંકન પૂર્ણ કરવા માટે સમય આપવાનું આભારી છું.",
  "secline": "તમારો સ્કોર છે",
  "thirdline": "જે દર્શાવે છે",
  "forthline": "તમારે મૂલ્યાંકન પરિણામો આધારે,",
  "fifthline": "અમે તમને માનસિક આરોગ્ય વિશેના પ્રાધિકારી સાથે પરામર્શ કરવા જઈએ છીએ.",
  "sixthline": "જો તમે યુ.કે.માં રહેતા હો તો તમે તમારી સ્થાનિક માનસિક આરોગ્ય સેવાઓનો સંપર્ક કરવા માટે નીચેની લિંકનો ઉપયોગ કરી શકો છો:",
  "sevenline": "તમારા જી.પી. શોધો - એન.એચ.એસ ટોકિંગ થેરાપી સેવા શોધો - એન.એચ.એસ",
  "mild": "હલકું",
  "mod": "મધ્યમ",
  "severe": "ગંભીર",
  "op1": "કોઈ ચિંતા રોગ નથી",
  "op2": "હલકી ચિંતા રોગ",
  "op3": "મધ્યમ ચિંતા રોગ",
  "op4": "ગંભીર ચિંતા રોગ",
  "op5": "કોઈ ઉદાસી",
  "op6": "હલકી ઉદાસી",
  "op7": "મધ્યમ ઉદાસી",
  "op8": "મધ્યમ ગંભીર ઉદાસી",
  "op9": "ગંભીર ઉદાસી",
  "op10": "ન્યુનતમ અસમર્થતા",
  "op11": "હલકી અસમર્થતા",
  "op12": "મધ્યમ અસમર્થતા",
  "op13": "ગંભીર અસમર્થતા",
  "op14": "કોઈ ચિંતા અને ઉદાસી રોગ નથી",
  "op15": "હલકી ચિંતા અને ઉદાસી રોગ",
  "op16": "મધ્યમ ચિંતા અને ઉદાસી રોગ",
  "op17": "ગંભીર ચિંતા અને ઉદાસી રોગ",
  "title": "માનસિક આરોગ્ય મૂલ્યાંકન એપ",
  "dashhello": "હેલો!",
  "dashslogan": "ચાલો તમારો માનસિક આરોગ્ય મૂલ્યાંકન કરીએ.",
  "wsastop": "મહેરબાની કરીને જાહેર કરો કે કેમ તમારા લક્ષણો દ્વારા પાછાળા સપ્તાહમાં તમારી કાર્ય અથવા સામાજિક જીવન પર કેટલી અસર થઈ છે",
  "toptext": "પાછલા બે અઠવાડિયામાં, નીચેના સમસ્યાઓ વડે તમે કેટલી વખત ચિંતિત થયા છો?",
  "qtnumber": "પ્રશ્ન",
  //શીર્ષકો
  "g7title": "સામાન્ય ચિંતા વ્યાધિ (GAD-7)",
  "p9title": "રોગી આરોગ્ય પ્રશ્નપત્ર (PHQ-9)",
  "wsastitle": "કામ અને સામાજિક સુયોજન સ્કેલ (WSAS)",
  //G7
  "g71": "ઘબરાહટ, ઉદ્વેગ અથવા નિરાશામાં અનુભવ કરવું.",
  "g72": "ચિંતા રોકવા અથવા નિયંત્રિત કરવામાં અસમર્થ હોવા.",
  "g73": "વિવિધ વસ્તુઓ વિશે ઘબરાવવું.",
  "g74": "વિશ્રામની સમસ્યા.",
  "g75": "એવી અસ્થિરતા કે બેઠવામાં મુશ્કેલી.",
  "g76": "સહજે ક્રોધિત અથવા ચિડખાવે છે.",
  "g77": "કંઈ ભયાનક થઈ જવાનું અનુભવ કરવું, જેમ કે કંઈ ખોટું થઈ શકે.",
  "op1": "બિલકુલ નહીં",
  "op2": "કેટલાક દિવસ",
  "op3": "સાધારણ દિવસો",
  "op4": "લગભગ પ્રતિદિન",
  //P9
  "p91": "કામમાં અથવા મનોરમ થવાની થોડી રમત નહીં.",
  "p92": "નિરાશ, ઉદાસ અથવા આત્મહત્યા નું અનુભવ કરવું.",
  "p93": "ઝડપથી પાંસલા નહીં મળવું, કેટલાક સમય સુધી ઊંચી જગ્યા પર જાવું અથવા અધિક ઊંચી જગ્યા પર સુધી જાવું.",
  "p94": "થકેલા અથવા થોડી ઊર્જા મળવી રહી છે.",
  "p95": "ખાણ-પીણામાં થોડી રહેઠાણ અથવા અધિક ખાણી.",
  "p96": "તમારા વિશે ખરાબ અનુભવ કરવું - અથવા તમે અસફળ અને તમારા પરિવાર અથવા તમારા આપણા પરિવાર માટે અસફળ અથવા તમારા પરિવાર માટે અસફળ અનુભવ કરવું.",
  "p97": "બધી વાતોને ધ્યાનમાં લાવવાની અથવા અખબાર વાંચવાની મુશ્કેલી.",
  "p98": "આવું કે બોલવું એવું ધીમે કે બીજા લોકો નોંધી શકે તેવું અથવા વિરુદ્ધ - એવું જેવું છે કે તમે હોય કે બીજા થી વધુ સામાન્ય પ્રમાણમાં અધિક હરકત કરવી શકો છો.",
  //WSAS
  "wsas1": "વ્યક્તિગત સંબંધો (ઉદાહરણ તરીકે: પરિવાર, મિત્રો, સહકર્મીઓ)",
  "wsas2": "કામ અથવા અધ્યયન (ઉદાહરણ તરીકે: અનુપસ્થિતિ, કમી ઉત્પાદકતા)",
  "wsas3": "ઘરની વ્યવસ્થા (ઉદાહરણ તરીકે: ઘરની રક્ષા, કામ પ્રદર્શન)",
  "wsas4": "સામાજિક વિનોદ (ઉદાહરણ તરીકે: શોખ, ખેલ, મનોરંજન)",
  "wsas5": "નિજી મનોરંજન (ઉદાહરણ તરીકે: વાંચવું, સંગીત સાંભળવું, ટીવી જોવું)",
  "wp1": "બિલકુલ અસર થયું નથી",
  "wp2": "થોડીવાર અસર થયું છે",
  "wp3": "મધ્યમ અસર થયું છે",
  "wp4": "પ્રચંડ અસર થયું છે",
  "wp5": "અત્યંત પ્રચંડ અસર થયું છે"
  },

////Arabic

  'ar_SA':{

  "starttitle": "لا يوفر التطبيق\nأو يقترح أي تشخيص",
  "startdesc": "يرجى استخدام هذا التطبيق فقط لتوجيه النتائج إلى\nأخصائي العلاج الخاص بك أو المتخصص في الصحة النفسية.",
  "firstline": "شكرًا لك على الوقت الذي قمت به في إكمال التقييمات الذاتية.",
  "secline": "نتيجتك هي",
  "thirdline": "التي تشير إلى",
  "forthline": "بناءً على نتائج التقييم الخاصة بك،",
  "fifthline": "نقترح عليك استشارة متخصص في الصحة النفسية.",
  "sixthline": "إذا كنت تعيش في المملكة المتحدة يمكنك الوصول إلى الرابط أدناه للاتصال بخدمات الصحة النفسية المحلية الخاصة بك:",
  "sevenline": "ابحث عن طبيبك - ابحث عن خدمات العلاج الحديثة NHS - NHS",
  "mild": "خفيف",
  "mod": "متوسط",
  "severe": "شديد",
  "op1": "لا يوجد اضطراب قلق",
  "op2": "اضطراب قلق خفيف",
  "op3": "اضطراب قلق متوسط",
  "op4": "اضطراب قلق شديد",
  "op5": "لا يوجد اكتئاب",
  "op6": "اكتئاب خفيف",
  "op7": "اكتئاب متوسط",
  "op8": "اكتئاب شديد متوسط",
  "op9": "اكتئاب شديد",
  "op10": "تقييد طفيف",
  "op11": "تقييد خفيف",
  "op12": "تقييد متوسط",
  "op13": "تقييد شديد",
  "op14": "لا يوجد اضطراب قلق ولا اكتئاب",
  "op15": "اضطراب قلق خفيف واكتئاب",
  "op16": "اضطراب قلق متوسط واكتئاب",
  "op17": "اضطراب قلق شديد واكتئاب",
  "title": "تطبيق تقييم الصحة العقلية",
  "dashhello": "مرحبًا!",
  "dashslogan": "دعونا نقيم صحتك العقلية.",
  "wsastop": "يرجى التحديد كم تم تأثير عملك أو حياتك الاجتماعية بسبب الأعراض الخاصة بك خلال الأسبوع الماضي",
  "toptext": "خلال الأسبوعين الماضيين، بمدى تكرر الإزعاج من المشاكل التالية؟",
  "qtnumber": "سؤال",
  // العناوين
  "g7title": "اضطراب القلق العام (GAD-7)",
  "p9title": "استبيان صحة المريض (PHQ-9)",
  "wsastitle": "مقياس التكيف العملي والاجتماعي (WSAS)",
  // G7
  "g71": "الشعور بالتوتر أو القلق أو الحافة.",
  "g72": "عدم القدرة على التوقف عن القلق أو السيطرة عليه.",
  "g73": "القلق الزائد بشأن أشياء مختلفة.",
  "g74": "مشكلة في الاسترخاء.",
  "g75": "الانزعاج الشديد حتى يصعب الجلوس بسكون.",
  "g76": "الانزعاج بسهولة أو التهيج.",
  "g77": "الشعور بالخوف، كما لو أن شيئًا فظيعًا قد يحدث.",
  "op1": "على الإطلاق لا",
  "op2": "عدة أيام",
  "op3": "أكثر من نصف الأيام",
  "op4": "تقريبا كل يوم",
  // P9
  "p91": "قليل من الاهتمام أو المتعة في القيام بالأشياء.",
  "p92": "الشعور بالحزن أو الاكتئاب أو اليأس.",
  "p93": "مشكلة في النوم أو البقاء نائمًا أو النوم أكثر من اللازم.",
  "p94": "الشعور بالتعب أو قلة الطاقة.",
  "p95": "فقدان الشهية أو الأكل بكثرة.",
  "p96": "الشعور بالسوء بنفسك - أو أنك فاشل أو أنك خذلت نفسك أو عائلتك.",
  "p97": "مشكلة في التركيز على الأشياء، مثل قراءة الصحف أو مشاهدة التلفاز.",
  "p98": "الحركة أو الكلام ببطء بحيث يمكن للآخرين أن يلاحظوا؟ أو العكس - كونك عصبيًا أو متوترًا بحيث تتحرك كثيرًا أكثر من المعتاد.",
  "p99": "أفكار بأنك ستكون أفضل في حالة موتك، أو بأذية نفسك بطريقة ما.",
  // WSAS
  "wsas1": "العلاقات الشخصية (مثل العائلة والأصدقاء والزملاء)",
  "wsas2": "العمل أو الدراسة (مثل الغياب عن العمل، والإنتاجية المنخفضة)",
  "wsas3": "إدارة المنزل (مثل الحفاظ على المنزل، وأداء المهام المنزلية)",
  "wsas4": "أنشطة الترفيه الاجتماعي (مثل الهوايات والرياضة والترفيه)",
  "wsas5": "أنشطة الترفيه الخاصة (مثل القراءة والاستماع إلى الموسيقى ومشاهدة التلفزيون)",
  "wp1": "لم يتأثر بتاتاً",
  "wp2": "تأثر طفيف",
  "wp3": "تأثر متوسط",
  "wp4": "تأثر بشكل كبير",
  "wp5": "تأثر بشكل شديد"
  },


//// chinese

  'zh_CN':{

  "starttitle": "应用程序不提供\n或建议任何诊断",
  "startdesc": "请仅将此应用程序用于将结果通知给您的\n治疗师或心理健康专业人士。",
  "firstline": "感谢您抽出时间完成自我评估。",
  "secline": "您的得分是",
  "thirdline": "表明",
  "forthline": "根据您的评估结果，",
  "fifthline": "我们建议您咨询心理健康专业人员。",
  "sixthline": "如果您居住在英国，可以使用下面的链接联系您当地的心理健康服务：",
  "sevenline": "寻找您的家庭医生 - 找到英国国家医疗服务的言语疗法服务 - NHS",
  "mild": "轻度",
  "mod": "中度",
  "severe": "严重",
  "op1": "没有焦虑障碍",
  "op2": "轻度焦虑障碍",
  "op3": "中度焦虑障碍",
  "op4": "严重焦虑障碍",
  "op5": "没有抑郁症",
  "op6": "轻度抑郁症",
  "op7": "中度抑郁症",
  "op8": "中重度抑郁症",
  "op9": "重度抑郁症",
  "op10": "轻微受损",
  "op11": "轻度受损",
  "op12": "中度受损",
  "op13": "严重受损",
  "op14": "没有焦虑障碍和抑郁症",
  "op15": "轻度焦虑障碍和抑郁症",
  "op16": "中度焦虑障碍和抑郁症",
  "op17": "严重焦虑障碍和抑郁症",
  "title": "心理健康评估应用程序",
  "dashhello": "你好！",
  "dashslogan": "让我们评估您的心理健康。",
  "wsastop": "请指出您的工作或社交生活在过去一周内受到症状影响的程度。",
  "toptext": "在过去两周内，您被以下问题困扰的频率有多高？",
  "qtnumber": "问题",
  // 标题
  "g7title": "广泛性焦虑障碍（GAD-7）",
  "p9title": "患者健康问卷（PHQ-9）",
  "wsastitle": "工作和社交适应量表（WSAS）",
  // G7
  "g71": "感觉紧张、焦虑或不安。",
  "g72": "无法停止或控制担忧。",
  "g73": "过分担心不同的事情。",
  "g74": "难以放松。",
  "g75": "变得如此不安静，以至于难以静坐。",
  "g76": "容易生气或恼火。",
  "g77": "感觉害怕，好像会发生可怕的事情。",
  "op1": "完全没有",
  "op2": "几天",
  "op3": "超过半数的日子",
  "op4": "几乎每天",
  // P9
  "p91": "对做事情感兴趣或享受的乐趣很少。",
  "p92": "感觉沮丧、压抑或绝望。",
  "p93": "入睡困难或保持睡眠，或睡眠时间过长。",
  "p94": "感觉疲倦或精力不足。",
  "p95": "食欲不佳或过度进食。",
  "p96": "感觉自己很差劲 - 或者认为自己是个失败者，或者认为自己辜负了自己或家人。",
  "p97": "注意力不集中，无法专注于事物，如阅读报纸或看电视。",
  "p98": "行动或说话速度变慢，以至于别人可能会注意到？或者相反 - 动来动去的，以至于比平时多动了很多。",
  "p99": "认为最好死了，或者以某种方式伤害自己的想法。",
  // WSAS
  "wsas1": "个人关系（如家人、朋友、同事）",
  "wsas2": "工作或学习（如缺勤、生产力下降）",
  "wsas3": "家庭管理（如维护家务、做家务）",
  "wsas4": "社交休闲活动（如爱好、运动、娱乐）",
  "wsas5": "私人休闲活动（如阅读、听音乐、看电视）",
  "wp1": "完全没有受到影响",
  "wp2": "轻微受影响",
  "wp3": "中度受影响",
  "wp4": "明显受影响",
  "wp5": "严重受影响"
  },


  ///slovakian


  'sk_SK':{

  "starttitle": "Aplikácia neposkytuje\nani nenavrhuje žiadnu diagnózu",
  "startdesc": "Prosím, používajte túto aplikáciu len na\nkomunikáciu výsledkov so svojím\nterapeutom alebo odborníkom na duševné zdravie.",
  "firstline": "Ďakujeme, že ste si na vyplnenie seba-hodnotení našli čas.",
  "secline": "Váš výsledok je",
  "thirdline": "čo naznačuje",
  "forthline": "Na základe vašich výsledkov vyhodnotenia",
  "fifthline": "odporúčame vám konzultovať s odborníkom na duševné zdravie.",
  "sixthline": "Ak žijete vo Veľkej Británii, môžete použiť nižšie uvedený odkaz na kontaktovanie miestnych služieb duševného zdravia:",
  "sevenline": "Nájsť svojho lekára - Nájsť službu hovorenej terapie NHS - NHS",
  "mild": "Mierne",
  "mod": "Stredné",
  "severe": "Vážne",
  "op1": "Žiadne úzkostné poruchy",
  "op2": "Mierne úzkostné poruchy",
  "op3": "Stredne ťažké úzkostné poruchy",
  "op4": "Vážne úzkostné poruchy",
  "op5": "Žiadna depresia",
  "op6": "Mierne depresie",
  "op7": "Stredne ťažká depresia",
  "op8": "Stredne závažná depresia",
  "op9": "Vážna depresia",
  "op10": "Minimálna porucha",
  "op11": "Mierne zhoršenie",
  "op12": "Stredne závažná porucha",
  "op13": "Vážne zhoršenie",
  "op14": "Žiadne úzkostné a depresívne poruchy",
  "op15": "Mierne úzkostné a depresívne poruchy",
  "op16": "Stredne závažné úzkostné a depresívne poruchy",
  "op17": "Vážne úzkostné a depresívne poruchy",
  "title": "Aplikácia na hodnotenie duševného zdravia",
  "dashhello": "Ahoj!",
  "dashslogan": "Hodnoťme vaše duševné zdravie.",
  "wsastop": "Prosím, uveďte, do akej miery boli vaše pracovné alebo sociálne životy ovplyvnené vašimi príznakmi počas minulého týždňa.",
  "toptext": "Počas posledných dvoch týždňov, ako často vás trápili nasledujúce problémy?",
  "qtnumber": "Otázka",
  // Nadpisy
  "g7title": "Generalizovaná úzkostná porucha (GAD-7)",
  "p9title": "Dotazník zdravia pacienta (PHQ-9)",
  "wsastitle": "Pracovná a sociálna škála prispôsobenia (WSAS)",
  // G7
  "g71": "Cítite sa nervózne, úzkostné alebo napäté.",
  "g72": "Nemôžete zastaviť alebo kontrolovať obavy.",
  "g73": "Príliš veľa obáv o rôzne veci.",
  "g74": "Máte problémy s uvoľňovaním.",
  "g75": "Ste takí nepokojní, že je ťažké sedieť v kľude.",
  "g76": "Stávate sa ľahko podráždenými alebo rozčúlenými.",
  "g77": "Cítite sa vystrašene, akoby sa niečo hrozné malo stať.",
  "op1": "Vôbec nie",
  "op2": "Niekoľko dní",
  "op3": "Väčšina dní",
  "op4": "Takmer každý deň",
  // P9
  "p91": "Málo záujmu alebo potešenia z činností.",
  "p92": "Cítite sa smutní, depresívni alebo zúfalí.",
  "p93": "Máte problémy s usínanim alebo spaním, alebo spíte príliš dlho.",
  "p94": "Cítite sa unavení alebo máte málo energie.",
  "p95": "Zlý chutný alebo prejedanie sa.",
  "p96": "Cítite sa zle sami o sebe - alebo si myslíte, že ste zlyhaním alebo ste zklamali seba alebo svoju rodinu.",
  "p97": "Máte problémy s sústredením sa na veci, ako je čítanie novín alebo sledovanie televízie.",
  "p98": "Pohybujete sa alebo hovoríte tak pomaly, že si ostatní mohli všimnúť? Alebo naopak - ste tak nervózni alebo nepokojní, že sa pohybujete oveľa viac ako obvykle.",
  "p99": "Máte myšlienky, že by ste boli lepší mŕtvi, alebo že by ste sebe alebo iným ublížili akýmkoľvek spôsobom.",
  // WSAS
  "wsas1": "Osobné vzťahy (napríklad rodina, priatelia, kolegovia)",
  "wsas2": "Práca alebo štúdium (napríklad absencia, znížená produktivita)",
  "wsas3": "Správa domácnosti (napríklad udržiavanie domácnosti, vykonávanie domácich prác)",
  "wsas4": "Sociálne voľnočasové aktivity (napríklad koníčky, šport, zábava)",
  "wsas5": "Súkromné voľnočasové aktivity (napríklad čítanie, počúvanie hudby, sledovanie televízie)",
  "wp1": "Vôbec neobmedzený",
  "wp2": "Trochu obmedzený",
  "wp3": "Stredne obmedzený",
  "wp4": "Značne obmedzený",
  "wp5": "Veľmi obmedzený"
  },


  ///somali

  'so_SO':{
  "starttitle": "App-madu waa aan siin\nama talo sugan noocaadu ugu dheeraato",
  "startdesc": "Fadlan isticmaal app-kan oo kaliya si aad u\nfarriin uga helto tababare ama\ndhakhtar caafimaadka maskaxda.",
  "firstline": "Mahadsanid in aad samayso waqti si aad u buuxiso\nliiska xogta xaggaaga.",
  "secline": "Natiijadaaga waxay tahay",
  "thirdline": "oo ku tilmaamay",
  "forthline": "Bartaada ee xogta xaggaaga ah,",
  "fifthline": "waxaan ku soo jeedinaynaa inaad kala shaqaysid\ncaafimaadka maskaxda.",
  "sixthline": "Haddii aad joogto UK, waxaad isticmaali kartaa\nalinka hoose si aad u wacdo adeegyada\nciidamada caafimaadka maskaxda ee ku yaal:",
  "sevenline": "Heli igaaga gudaha - Heli adeegyada teraapiyada hadal NHS - NHS",
  "mild": "Adkaadid",
  "mod": "Dhexe",
  "severe": "Dareen weyn",
  "op1": "Nala qabto cabsi",
  "op2": "Adkaada cabsi",
  "op3": "Cabsi dhexe",
  "op4": "Cabsi dareen weyn",
  "op5": "Ma jiro dabcan",
  "op6": "Adkaada dabcan",
  "op7": "Dabcan dhexe",
  "op8": "Dabcan dareen weyn dhexe",
  "op9": "Dabcan dareen weyn",
  "op10": "Xaalad yar",
  "op11": "Adkaada yar",
  "op12": "Dabcan dhexe",
  "op13": "Dabcan dareen weyn",
  "op14": "Ma jiro cabsi iyo dabcan",
  "op15": "Adkaada cabsi iyo dabcan",
  "op16": "Cabsi dhexe iyo dabcan",
  "op17": "Cabsi dareen weyn iyo dabcan",
  "title": "Hagaajinta Nafteyda Caafimaadka Magac",
  "dashhello": "Marhaba!",
  "dashslogan": "Nagu hagaaji nafteyda caafimaadka.",
  "wsastop": "Fadlan wax ka beddel marka ayada in aad sii badasho sida aad uga xanuunsan lahayd shaqo ama nolosha bulshadeed ee toddobaadkan hore.",
  "toptext": "Xilliyo todobaad ah, waxa ugu yaraan halkii ay kugu qaban lahayd dhacdooyinka hoose ee hoose?",
  "qtnumber": "Suaal",
  // Mukhtaarada
  "g7title": "Marxad ay Nafteyda Dadweynaha (GAD-7)",
  "p9title": "Soo Gudbinta Caafimaadka Maraykanka (PHQ-9)",
  "wsastitle": "Cabbirka Shaqo iyo Bulsho (WSAS)",
  // G7
  "g71": "Arrin ka mid ah xasilloonida, cabsida ama khataraha.",
  "g72": "Majirto in aad joojiso ama ka dhaqdo xasilloon.",
  "g73": "Xasillo badan oo ku saabsan waxyaabo kala duwan.",
  "g74": "Dhibaato la'aanta.",
  "g75": "In uu tahay in aad ka duwan tahay in aad ku xidhan tahay.",
  "g76": "In uu aad yeesho indhaha ama uu aad ka geynayo farxad.",
  "g77": "Xasillo ka timid, sida wax fiican oo ku dhacaya.",
  "op1": "Kama dambayn",
  "op2": "Maalmaha badan",
  "op3": "Dhexe leh maalmaha",
  "op4": "Magaalada dhan",
  // P9
  "p91": "Rajo ama farxad xun oo laga heli karo wax kasta oo shaqooyinka.",
  "p92": "Xasillo, kala go' iyo isku mid ah.",
  "p93": "Dhibaato ka dhigan ama sii kiciya ama indhaha weyn.",
  "p94": "Xasillo ama tillaabo aad u yar oo ku xad gudub.",
  "p95": "Marta kara ama markii aad dhaqaaqo adagi.",
  "p96": "Xasillo aad ku jirtid ee aad tahay oo aad tahay mid khalad ama aad dhalisid nafsiyadaada ama qoyskiinnada ama qoysk.",
  "p97": "Dhibaato u yeeli kara arrimaha, sida akhbaariga akhbaariga ama fiidiyowga fiidiyowga.",
  "p98": "Liiska ama hadal buuxa ah ee qofku waxaa uu ku noqon karaa? Ama dibadda - in aad ka geysan tahay ama aad ka calmadow tahay in aad u gudboobi kartid iyadoo aad jirtid wakhti badan.",
  "p99": "Fikir badan oo aad u yeelayso in aad aad u fiican tahay xilliga in aad ku noqon lahayd ama xayawaanadaaga mid ka mid ah.",
  // WSAS
  "wsas1": "Dhaqaale deg deg ah (sida qoysaska, saaxiibada, xubnaha shaqaalaha)",
  "wsas2": "Shaqaale ama dugsi (sida gaariga, dhaqan gelinta isbeddelka)",
  "wsas3": "Maamulka guri (sida guryaha xiran, tijaabada xogta guriga)",
  "wsas4": "Habka guud (sida laabto, ciyaaraha, dhibcaha)",
  "wsas5": "Habka gaarka ah (sida akhri, maqal, fiidiyowga teliwisyoonka)",
  "wp1": "Kama dambayn la xad gudubtay",
  "wp2": "Labaabo xad gudubtay",
  "wp3": "Midka xad gudubtay",
  "wp4": "Xiiso leh xad gudubtay",
  "wp5": "Ka qaybqaadanna wayn xad gudubtay"
  },




  };

}